complete -x -c hem  -l debug --description 'Enable debugging';
complete -x -c hem  -l ansi --description 'Enable / disable ansi output';
complete  -c hem  -l log-level --description 'Set log level';
complete -x -c hem  -l non-interactive --description 'Run non-interactively. Defaults will be automatically used where possible.';
complete -x -c hem  -l skip-host-checks --description 'Skip host checks';
complete -x -c hem -s a -l all --description 'Show hidden commands';
complete -x -c hem -s h -l help --description 'Display help';
complete -x -c hem -s v -l version --description 'Print version information';
complete -x -c hem -n '__hem_scope_test hem plugin' -a install --description 'Install a project's defined Hemfile plugins';
complete -x -c hem -n '__hem_scope_test hem plugin install' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem plugin' -a update --description 'Update a project's defined Hemfile plugins';
complete -x -c hem -n '__hem_scope_test hem plugin update' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem assets' -a download --description 'Download project assets';
complete  -c hem -n '__hem_scope_test hem assets download' -s e -l env --description 'Environment';
complete -x -c hem -n '__hem_scope_test hem assets download download' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem assets' -a upload --description 'Upload project assets';
complete  -c hem -n '__hem_scope_test hem assets upload' -s e -l env --description 'Environment';
complete -x -c hem -n '__hem_scope_test hem assets upload upload' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem assets' -a apply --description 'Apply project assets';
complete  -c hem -n '__hem_scope_test hem assets apply' -s a -l applicator --description 'Asset applicator to apply, default all';
complete  -c hem -n '__hem_scope_test hem assets apply apply' -s e -l env --description 'Environment';
complete -x -c hem -n '__hem_scope_test hem assets apply apply apply' -s f -l force --description 'Force application of already applied assets';
complete -x -c hem -n '__hem_scope_test hem assets apply apply apply apply' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem' -a assets --description 'Project asset commands';
complete -x -c hem -n '__hem_scope_test hem assets' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem' -a config --description 'Configure hem';
complete -x -c hem -n '__hem_scope_test hem config' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem deps' -a gems --description 'Install Gem dependencies';
complete -x -c hem -n '__hem_scope_test hem deps gems' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem deps' -a composer --description 'Install composer dependencies';
complete -x -c hem -n '__hem_scope_test hem deps composer' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem deps' -a vagrant_plugins --description 'Install vagrant plugins';
complete -x -c hem -n '__hem_scope_test hem deps vagrant_plugins' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem deps' -a chef --description 'Install chef dependencies';
complete -x -c hem -n '__hem_scope_test hem deps chef' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem' -a deps --description 'Dependency related tasks';
complete -x -c hem -n '__hem_scope_test hem deps' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem mysql' -a console --description 'Open a MySQL cli connection';
complete  -c hem -n '__hem_scope_test hem mysql console' -s D -l db --description 'Database';
complete -x -c hem -n '__hem_scope_test hem mysql console console' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem' -a mysql --description 'MySQL related commands';
complete -x -c hem -n '__hem_scope_test hem mysql' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem redis' -a cli --description 'Open a Redis cli connection';
complete -x -c hem -n '__hem_scope_test hem redis cli' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem redis' -a flush --description 'Flush some or all redis dbs';
complete -x -c hem -n '__hem_scope_test hem redis flush' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem' -a redis --description 'Redis related commands';
complete -x -c hem -n '__hem_scope_test hem redis' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem seed' -a plant --description 'Create a new project from a seed repository';
complete  -c hem -n '__hem_scope_test hem seed plant' -s g -l git-url --description 'Git repository for project';
complete  -c hem -n '__hem_scope_test hem seed plant plant' -s s -l seed --description 'Seed name or URL to use';
complete  -c hem -n '__hem_scope_test hem seed plant plant plant' -s b -l branch --description 'Seed branch to use';
complete  -c hem -n '__hem_scope_test hem seed plant plant plant plant' -s d -l data --description 'Seed data to save to the project hem configuration';
complete -x -c hem -n '__hem_scope_test hem seed plant plant plant plant plant' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem' -a seed --description 'Project seed commands';
complete -x -c hem -n '__hem_scope_test hem seed' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem self' -a repl --description 'REPL';
complete -x -c hem -n '__hem_scope_test hem self repl' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem self debug' -a paths --description 'Display project paths';
complete -x -c hem -n '__hem_scope_test hem self debug paths' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem self debug' -a locate --description 'Locate';
complete -x -c hem -n '__hem_scope_test hem self debug locate' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem self' -a debug --description 'Tasks for debugging hem';
complete -x -c hem -n '__hem_scope_test hem self debug' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem' -a self --description 'Internal hem debugging tools';
complete -x -c hem -n '__hem_scope_test hem self' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem system' -a check --description 'Check system configuration for potential problems';
complete -x -c hem -n '__hem_scope_test hem system check' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem system completions' -a install --description 'Install shell completion helpers';
complete -x -c hem -n '__hem_scope_test hem system completions install' -s f -l fish --description 'Install completions for FISH';
complete -x -c hem -n '__hem_scope_test hem system completions install install' -s b -l bash --description 'Install completions for Bash';
complete -x -c hem -n '__hem_scope_test hem system completions install install install' -s z -l zsh --description 'Install completions for ZSH';
complete -x -c hem -n '__hem_scope_test hem system completions install install install install' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem system completions' -a fish --description 'Display FISH shell completion commands';
complete -x -c hem -n '__hem_scope_test hem system completions fish' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem system' -a completions --description 'Shell completion related commands';
complete -x -c hem -n '__hem_scope_test hem system completions' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem' -a system --description 'System configuration related commands';
complete -x -c hem -n '__hem_scope_test hem system' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem tools' -a composer --description 'Fetch composer';
complete -x -c hem -n '__hem_scope_test hem tools composer' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem' -a tools --description 'Tasks to retrieve common tools';
complete -x -c hem -n '__hem_scope_test hem tools' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem vm' -a stop --description 'Stop VM';
complete -x -c hem -n '__hem_scope_test hem vm stop' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem vm' -a rebuild --description 'Rebuild VM';
complete -x -c hem -n '__hem_scope_test hem vm rebuild' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem vm' -a destroy --description 'Destroy VM';
complete -x -c hem -n '__hem_scope_test hem vm destroy' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem vm' -a start --description 'Start VM without provision';
complete -x -c hem -n '__hem_scope_test hem vm start' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem vm' -a reload --description 'Reload VM';
complete -x -c hem -n '__hem_scope_test hem vm reload' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem vm' -a provision --description 'Provision VM';
complete -x -c hem -n '__hem_scope_test hem vm provision' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem vm' -a ssh --description 'Open an SSH connection';
complete -x -c hem -n '__hem_scope_test hem vm ssh' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem vm' -a mysql --description 'Open a MySQL cli connection';
complete  -c hem -n '__hem_scope_test hem vm mysql' -s D -l db --description 'Database';
complete -x -c hem -n '__hem_scope_test hem vm mysql mysql' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem vm' -a redis --description 'Open a Redis cli connection';
complete -x -c hem -n '__hem_scope_test hem vm redis' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem' -a vm --description 'VM related commands';
complete -x -c hem -n '__hem_scope_test hem vm' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem magento cache' -a clear --description 'Clear cache';
complete -x -c hem -n '__hem_scope_test hem magento cache clear' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem magento' -a cache --description 'Cache tasks';
complete -x -c hem -n '__hem_scope_test hem magento cache' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem magento config' -a configure-urls --description 'Update base urls';
complete -x -c hem -n '__hem_scope_test hem magento config configure-urls' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem magento config' -a enable-errors --description 'Enable magento errors';
complete -x -c hem -n '__hem_scope_test hem magento config enable-errors' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem magento config' -a create-admin-user --description 'Create admin user';
complete -x -c hem -n '__hem_scope_test hem magento config create-admin-user' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem magento config' -a enable-rewrites --description 'Enable rewrites';
complete -x -c hem -n '__hem_scope_test hem magento config enable-rewrites' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem magento' -a config --description 'Configuration related tasks';
complete -x -c hem -n '__hem_scope_test hem magento config' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem magento patches' -a apply --description 'Apply patches to Magento';
complete -x -c hem -n '__hem_scope_test hem magento patches apply' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem magento' -a patches --description 'Patch tasks';
complete -x -c hem -n '__hem_scope_test hem magento patches' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem magento setup-scripts' -a run --description 'Run magento setup scripts';
complete -x -c hem -n '__hem_scope_test hem magento setup-scripts run' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem magento' -a setup-scripts --description 'Setup script tasks';
complete -x -c hem -n '__hem_scope_test hem magento setup-scripts' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem magento tools' -a n98magerun --description 'Fetches the n98-magerun utility';
complete -x -c hem -n '__hem_scope_test hem magento tools n98magerun' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem magento' -a initialize-vm --description 'Initializes magento specifics on the virtual machine after a fresh build';
complete -x -c hem -n '__hem_scope_test hem magento initialize-vm' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem' -a magento --description 'Magento related tasks';
complete -x -c hem -n '__hem_scope_test hem magento' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem selenium' -a install --description 'Install Selenium';
complete -x -c hem -n '__hem_scope_test hem selenium install' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem selenium' -a start --description 'Start Selenium';
complete -x -c hem -n '__hem_scope_test hem selenium start' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem selenium' -a stop --description 'Stop Selenium';
complete -x -c hem -n '__hem_scope_test hem selenium stop' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem selenium' -a forward --description 'Forward selenium connection to vm';
complete -x -c hem -n '__hem_scope_test hem selenium forward' -s h -l help --description 'Display help';
complete -x -c hem -n '__hem_scope_test hem' -a selenium --description 'Selenium tasks';
complete -x -c hem -n '__hem_scope_test hem selenium' -s h -l help --description 'Display help';